# docker-compose.yml
version: '3.8'

services:
  trackly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11888:11888"  # Main application port
    volumes:
      - /mnt/ssd/media/music:/music:ro  # Read-only mount of music directory
      - /home/long/docker/trackly/data:/data  # Persistent storage directory
    environment:
      - UPDATE_INTERVAL=0 0 * * *  # Set this to your desired cron schedule
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/dummy # Dummy webhook
      - NOTIFY_ON_SCAN=false  # Set to receive notifications for each scan completion
      - DISCORD_NOTIFY=false  # Set to false to disable discord notifications during scan
    restart: unless-stopped
    container_name: trackly-test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11888/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
